### ISSUE TITLE
Use the userId get parameter to plug it into the Javascript

### ISSUE THREAD

**Issue by gholtslander-va** [holtscomm/survey#22]
This seems slightly less gross than grabbing it out of the DOM? So what will happen is the URL will be `/survey/?userId=1234`, and in `Survey.componentDidMount` it could use some function to pull that userId out of the URL. It isn't perfect in Javascript, but then when we get to the point where we're getting people to just do the quiz we'd be able to remove the text on the screen that says things like, "You're userId whatever, use this link to bookmark your place and what not" (though that may be useful still)

**Comment by gholtslander** [comment]
"slightly less gross"
I do like the levels of elegance you are pushing for.

On Wed, Oct 14, 2015 at 7:00 AM, Graham Holtslander <
notifications@github.com> wrote:

> This seems slightly less gross than grabbing it out of the DOM? So what
> will happen is the URL will be /survey/?userId=1234, and in
> Survey.componentDidMount it could use some function to pull that userId
> out of the URL. It isn't perfect in Javascript, but then when we get to the
> point where we're getting people to just do the quiz we'd be able to remove
> the text on the screen that says things like, "You're userId whatever, use
> this link to bookmark your place and what not" (though that may be useful
> still)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/holtscomm/survey/issues/22>.
>



-- 
--
Gord
Gordon Holtslander, BEd
Partner, Holtslander Communications
holtslandercommunications.ca
gordon@holtslander.com

**Comment by gholtslander-va** [comment]
It's only gross from a developer perspective, users won't notice the difference at all. Thus, I'm a bit less willing to pull punches on describing the grossocity, if you will.

**Comment by gholtslander-va** [comment]
I think I'll only spend more time on this once we know our strategy for getting people paid-for and moving into the survey.
